-- ==============================================================================
-- SnowID Database Schema & Direct Integration Examples
-- Demonstrates Zero-Application-Side ID Generation
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- OPTION A: Using the Native High-Performance Rust Extension (snowid_pg)
-- Best for self-hosted PostgreSQL or environments supporting C/Rust extensions
-- ------------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS snowid;

CREATE TABLE orders_native (
    id BIGINT PRIMARY KEY DEFAULT snowid(), -- Automatically generated by Postgres!
    customer_name TEXT NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Example: Application inserts rows directly WITHOUT generating IDs first
INSERT INTO orders_native (customer_name, total_amount)
VALUES
    ('Alice Smith', 129.99),
    ('Bob Jones', 49.50)
RETURNING id, customer_name, total_amount;


-- ------------------------------------------------------------------------------
-- OPTION B: Using Pure SQL / PL/pgSQL function (for Managed Cloud DBs)
-- Best for AWS RDS, Supabase, Neon, GCP Cloud SQL
-- First run sql/postgres_pure.sql to define snowid_next()
-- ------------------------------------------------------------------------------
CREATE TABLE orders_cloud (
    id BIGINT PRIMARY KEY DEFAULT snowid_next(1), -- Using machine_id = 1
    customer_name TEXT NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Example: Application inserts rows directly WITHOUT generating IDs first
INSERT INTO orders_cloud (customer_name, total_amount)
VALUES
    ('Charlie Brown', 89.00),
    ('Diana Prince', 299.99)
RETURNING id, customer_name, total_amount;


-- ------------------------------------------------------------------------------
-- Inspecting / Decoding Generated IDs Directly in SQL
-- ------------------------------------------------------------------------------
SELECT
    id,
    customer_name,
    d.*
FROM orders_cloud,
LATERAL snowid_decode(orders_cloud.id) AS d;
